# Generated by Django 5.2 on 2025-05-22 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Spec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PartSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcBuilder.part')),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcBuilder.spec')),
            ],
        ),
        migrations.CreateModel(
            name='CompatibilityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partSpec_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compat_partspec_1', to='pcBuilder.partspec')),
                ('partSpec_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compat_partspec_2', to='pcBuilder.partspec')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcBuilder.part')),
            ],
        ),
        migrations.CreateModel(
            name='build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('input', models.JSONField()),
                ('partPercentage', models.JSONField()),
                ('budget', models.DecimalField(decimal_places=0, max_digits=12)),
                ('star', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Cpu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cpu', to='pcBuilder.product')),
                ('CpuCooler', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cpuCooler', to='pcBuilder.product')),
                ('Gpu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gpu', to='pcBuilder.product')),
                ('Monitor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monitor', to='pcBuilder.product')),
                ('MotherBoard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='motherboard', to='pcBuilder.product')),
                ('Power', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='power', to='pcBuilder.product')),
                ('Ram', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ram', to='pcBuilder.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcBuilder.product')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('date', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcBuilder.product')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcBuilder.productlink')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('part_spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcBuilder.partspec')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcBuilder.product')),
            ],
        ),
    ]
